link:
	ln -s ../local.properties AndEngine
	ln -s ../local.properties AndEngineSVGTextureRegionExtension
	ln -s ../local.properties AndEngineTexturePackerExtension
	ln -s ../local.properties solar
	ln -s ../local.properties utils

clean:
	rm AndEngine/local.properties
	rm AndEngineSVGTextureRegionExtension/local.properties
	rm AndEngineTexturePackerExtension/local.properties
	rm solar/local.properties
	rm utils/local.properties
