link:
	ln -s ../local.properties AndEngine
	ln -s ../local.properties AndEnginePhysicsBox2DExtension
	ln -s ../local.properties FlyingDandelion

clean:
	rm AndEngine/local.properties
	rm AndEnginePhysicsBox2DExtension/local.properties
	rm FlyingDandelion/local.properties
