link:
	ln -s ../local.properties AndEngine
	ln -s ../local.properties AndEngineAugmentedRealityExtension
	ln -s ../local.properties AndEngineCocosBuilderExtension
	ln -s ../local.properties AndEngineCocosBuilderExtensionCCRotatingSpriteExtension
	ln -s ../local.properties AndEngineExamples
	ln -s ../local.properties AndEngineLiveWallpaperExtension
	ln -s ../local.properties AndEngineMODPlayerExtension
	ln -s ../local.properties AndEngineMultiplayerExtension
	ln -s ../local.properties AndEngineMultiTouchExtension
	ln -s ../local.properties AndEnginePhysicsBox2DExtension
	ln -s ../local.properties AndEngineRobotiumExtension
	ln -s ../local.properties AndEngineRobotiumExtensionExample
	ln -s ../local.properties AndEngineRobotiumExtensionExampleTest
	ln -s ../local.properties AndEngineScriptingExtension
	ln -s ../local.properties AndEngineScriptingExtensionGenerator
	ln -s ../local.properties AndEngineServerExtension
	ln -s ../local.properties AndEngineSpineExtension
	ln -s ../local.properties AndEngineSVGTextureRegionExtension
	ln -s ../local.properties AndEngineTest
	ln -s ../local.properties AndEngineTexturePackerExtension
	ln -s ../local.properties AndEngineTMXTiledMapExtension

clean:
	rm AndEngine/local.properties
	rm AndEngineAugmentedRealityExtension/local.properties
	rm AndEngineCocosBuilderExtension/local.properties
	rm AndEngineCocosBuilderExtensionCCRotatingSpriteExtension/local.properties
	rm AndEngineExamples/local.properties
	rm AndEngineLiveWallpaperExtension/local.properties
	rm AndEngineMODPlayerExtension/local.properties
	rm AndEngineMultiplayerExtension/local.properties
	rm AndEngineMultiTouchExtension/local.properties
	rm AndEnginePhysicsBox2DExtension/local.properties
	rm AndEngineRobotiumExtension/local.properties
	rm AndEngineRobotiumExtensionExample/local.properties
	rm AndEngineRobotiumExtensionExampleTest/local.properties
	rm AndEngineScriptingExtension/local.properties
	rm AndEngineScriptingExtensionGenerator/local.properties
	rm AndEngineServerExtension/local.properties
	rm AndEngineSpineExtension/local.properties
	rm AndEngineSVGTextureRegionExtension/local.properties
	rm AndEngineTest/local.properties
	rm AndEngineTexturePackerExtension/local.properties
	rm AndEngineTMXTiledMapExtension/local.properties

