
gride:
	./cartesian_plane_grid.sh
plane:
	./cartesian_plane.sh
tank:
	./tank.sh
new:
	./create_image.sh tank 720 1280
	cp tank_grid.png ../assets/gfx/tank.png
clean:
	rm *.png
	rm ../assets/gfx/tank.png
