
gride:
	./cartesian_plane_grid.sh
plane:
	./cartesian_plane.sh
tank:
	./tank.sh
new:
	./create_image.sh tank 73 132 green
	./create_image.sh helicopter 73 132 blue
	./create_image.sh jeep 73 132 red
	cp helicopter_grid.png ../assets/gfx/helicopter.png
	cp jeep_grid.png       ../assets/gfx/jeep.png
	cp tank_grid.png       ../assets/gfx/tank.png

clean:
	rm ../assets/gfx/helicopter.png
	rm ../assets/gfx/jeep.png
	rm ../assets/gfx/tank.png
	rm *.png
