local:
	ln -s ../local.properties AndEngine
	ln -s ../local.properties AndEngineAugmentedRealityExtension
	ln -s ../local.properties AndEngineDebugDrawExtension
	ln -s ../local.properties AndEngineExamples
	ln -s ../local.properties AndEngineLiveWallpaperExtension
	ln -s ../local.properties AndEngineMODPlayerExtension
	ln -s ../local.properties AndEngineMultiplayerExtension
	ln -s ../local.properties AndEnginePhysicsBox2DExtension
	ln -s ../local.properties AndEngineSampleProject
	ln -s ../local.properties AndEngineScriptingExtension
	ln -s ../local.properties AndEngineSVGTextureRegionExtension
	ln -s ../local.properties AndEngineTexturePackerExtension
	ln -s ../local.properties AndEngineTMXTiledMapExtension
clean:
	rm AndEngine/local.properties
	rm AndEngineAugmentedRealityExtension/local.properties
	rm AndEngineDebugDrawExtension/local.properties
	rm AndEngineExamples/local.properties
	rm AndEngineLiveWallpaperExtension/local.properties
	rm AndEngineMODPlayerExtension/local.properties
	rm AndEngineMultiplayerExtension/local.properties
	rm AndEnginePhysicsBox2DExtension/local.properties
	rm AndEngineSampleProject/local.properties
	rm AndEngineScriptingExtension/local.properties
	rm AndEngineSVGTextureRegionExtension/local.properties
	rm AndEngineTexturePackerExtension/local.properties
	rm AndEngineTMXTiledMapExtension/local.properties
