local: config
	ln -s ../local.properties AndEngine/local.properties
	ln -s ../local.properties AndEngineAugmentedRealityExtension/local.properties
	ln -s ../local.properties AndEngineExamples/local.properties
	ln -s ../local.properties AndEngineLiveWallpaperExtension/local.properties
	ln -s ../local.properties AndEngineMODPlayerExtension/local.properties
	ln -s ../local.properties AndEngineMultiplayerExtension/local.properties
	ln -s ../local.properties AndEnginePhysicsBox2DExtension/local.properties
	ln -s ../local.properties AndEngineScriptingExtension/local.properties
	ln -s ../local.properties AndEngineSVGTextureRegionExtension/local.properties
	ln -s ../local.properties AndEngineTexturePackerExtension/local.properties
	ln -s ../local.properties AndEngineTMXTiledMapExtension/local.properties
	ln -s ../local.properties AndEngineDebugDrawExtension/local.properties
	ln -s ../../local.properties examples/01-SoundExample/local.properties
	ln -s ../../local.properties examples/02-SoundExample/local.properties
	ln -s ../../local.properties examples/AndengineMarioEx/local.properties
clean:
	rm AndEngine/local.properties
	rm AndEngineAugmentedRealityExtension/local.properties
	rm AndEngineExamples/local.properties
	rm AndEngineLiveWallpaperExtension/local.properties
	rm AndEngineMODPlayerExtension/local.properties
	rm AndEngineMultiplayerExtension/local.properties
	rm AndEnginePhysicsBox2DExtension/local.properties
	rm AndEngineScriptingExtension/local.properties
	rm AndEngineSVGTextureRegionExtension/local.properties
	rm AndEngineTexturePackerExtension/local.properties
	rm AndEngineTMXTiledMapExtension/local.properties
	rm examples/01-SoundExample/local.properties
	rm examples/02-SoundExample/local.properties
	rm examples/AndengineMarioEx/local.properties
	rm AndEngineDebugDrawExtension/local.properties
	rm AndEngineDebugDrawExtension

config:
	ln -s AndEngineDebugDrawExtension-GLES2                          AndEngineDebugDrawExtension
	# ln -s AndEngineDebugDrawExtension-GLES2-old-and-broken           AndEngineDebugDrawExtension

	# ln -s AndEngineDebugDrawExtension-GLES2-AnchorCenter             AndEngineDebugDrawExtension
	# ln -s AndEngineDebugDrawExtension-GLES2-AnchorCenter-latest-B2D  AndEngineDebugDrawExtension
	# ln -s AndEngineDebugDrawExtension-GLES2-latest-B2D               AndEngineDebugDrawExtension


