local: config
	ln -s ../local.properties AndEngine/
	ln -s ../local.properties AndEngineAugmentedRealityExtension/
	ln -s ../local.properties AndEngineExamples/
	ln -s ../local.properties AndEngineLiveWallpaperExtension/
	ln -s ../local.properties AndEngineMODPlayerExtension/
	ln -s ../local.properties AndEngineMultiplayerExtension/
	ln -s ../local.properties AndEnginePhysicsBox2DExtension/
	ln -s ../local.properties AndEngineScriptingExtension/
	ln -s ../local.properties AndEngineSVGTextureRegionExtension/
	ln -s ../local.properties AndEngineTexturePackerExtension/
	ln -s ../local.properties AndEngineTMXTiledMapExtension/
	ln -s ../local.properties AndEngineRobotiumExtensionExample/
	ln -s ../local.properties AndEngineRobotiumExtension/
	ln -s ../local.properties AndEngineRobotiumExtensionExampleTest/
	ln -s ../local.properties AndEngineDebugDrawExtension/local.properties
	ln -s ../../local.properties examples/01-SoundExample/local.properties
	ln -s ../../local.properties examples/02-SoundExample/local.properties
	ln -s ../../local.properties examples/AndEngineMarioEx/local.properties
clean:
	rm AndEngine/local.properties
	rm AndEngineAugmentedRealityExtension/local.properties
	rm AndEngineExamples/local.properties
	rm AndEngineLiveWallpaperExtension/local.properties
	rm AndEngineMODPlayerExtension/local.properties
	rm AndEngineMultiplayerExtension/local.properties
	rm AndEnginePhysicsBox2DExtension/local.properties
	rm AndEngineScriptingExtension/local.properties
	rm AndEngineSVGTextureRegionExtension/local.properties
	rm AndEngineTexturePackerExtension/local.properties
	rm AndEngineTMXTiledMapExtension/local.properties
	rm examples/01-SoundExample/local.properties
	rm examples/02-SoundExample/local.properties
	rm examples/AndEngineMarioEx/local.properties
	rm AndEngineDebugDrawExtension/local.properties
	rm AndEngineRobotiumExtensionExample/local.properties
	rm AndEngineRobotiumExtension/local.properties
	rm AndEngineRobotiumExtensionExampleTest/local.properties
	rm AndEngineDebugDrawExtension

config:
	ln -s AndEngineDebugDrawExtension-GLES2                          AndEngineDebugDrawExtension
	# ln -s AndEngineDebugDrawExtension-GLES2-old-and-broken           AndEngineDebugDrawExtension

	# ln -s AndEngineDebugDrawExtension-GLES2-AnchorCenter             AndEngineDebugDrawExtension
	# ln -s AndEngineDebugDrawExtension-GLES2-AnchorCenter-latest-B2D  AndEngineDebugDrawExtension
	# ln -s AndEngineDebugDrawExtension-GLES2-latest-B2D               AndEngineDebugDrawExtension


