link:
	ln -s ../local.properties AndEngine
	ln -s ../local.properties AndEngineAugmentedRealityExtension
	ln -s ../local.properties AndEngineCocosBuilderExtension
	ln -s ../local.properties AndEngineCocosBuilderExtensionCCRotatingSpriteExtension
	ln -s ../local.properties AndEngineDebugDrawExtension
	ln -s ../local.properties AndEngineExamples
	ln -s ../local.properties AndEngineLiveWallpaperExtension
	ln -s ../local.properties AndEngineMarioEx
	ln -s ../local.properties AndEngineMODPlayerExtension
	ln -s ../local.properties AndEngineMultiplayerExtension
	ln -s ../local.properties AndEngine_nazgee
	ln -s ../local.properties AndEnginePhysicsBox2DExtension
	ln -s ../local.properties AndEngineScriptingExtension
	ln -s ../local.properties AndEngineSVGTextureRegionExtension
	ln -s ../local.properties AndEngineTexturePackerExtension
	ln -s ../local.properties AndEngineTMXTiledMapExtension
	ln -s ../local.properties flower
	ln -s ../local.properties FlyingDandelion
	ln -s ../local.properties utils

clean:
	rm AndEngine/local.properties
	rm AndEngineAugmentedRealityExtension/local.properties
	rm AndEngineCocosBuilderExtension/local.properties
	rm AndEngineCocosBuilderExtensionCCRotatingSpriteExtension/local.properties
	rm AndEngineDebugDrawExtension/local.properties
	rm AndEngineExamples/local.properties
	rm AndEngineLiveWallpaperExtension/local.properties
	rm AndEngineMarioEx/local.properties
	rm AndEngineMODPlayerExtension/local.properties
	rm AndEngineMultiplayerExtension/local.properties
	rm AndEngine_nazgee/local.properties
	rm AndEnginePhysicsBox2DExtension/local.properties
	rm AndEngineScriptingExtension/local.properties
	rm AndEngineSVGTextureRegionExtension/local.properties
	rm AndEngineTexturePackerExtension/local.properties
	rm AndEngineTMXTiledMapExtension/local.properties
	rm flower/local.properties
	rm FlyingDandelion/local.properties
	rm utils/local.properties
